### ISSUE TITLE
+++ build-image.sh: need at least ssh key or password (error)

### ISSUE THREAD

**Issue by delassio** [oracle/oracle-linux#100]
Hello,

when running  ./bin/build-image.sh with defaults env  proprieties files , with all Mandatory parameters set, i get error that SSH_PASSWORD (Optional parameters) is not set

should  SSH_PASSWORD  be as Mandatory parameters ?

Thanks

**Comment by AmedeeBulle** [comment]
We need a way to connect to the instance.
That can be done either with a password or providing an ssh key pair.

The `SSH_PASSWORD` property is not mandatory, but if you don't set it, you have to provide an ssh key (`SSH_KEY_FILE`) 

Hope this clarifies

**Comment by delassio** [comment]
for that SSH_KEY_FILE is mandatory

**Comment by delassio** [comment]
> We need a way to connect to the instance.
> 
> That can be done either with a password or providing an ssh key pair.
> 
> 
> 
> The `SSH_PASSWORD` property is not mandatory, but if you don't set it, you have to provide an ssh key (`SSH_KEY_FILE`) 
> 
> 
> 
> Hope this clarifies

Thanks, if isn't mandatory why we get error message and the build failed

**Comment by AmedeeBulle** [comment]
I am not sure where you want to go with this...

We have:
https://github.com/oracle/oracle-linux/blob/490ac11f60c93c7babf67116d634c565d9353e80/oracle-linux-image-tools/env.properties.defaults#L30-L32

and:
https://github.com/oracle/oracle-linux/blob/490ac11f60c93c7babf67116d634c565d9353e80/oracle-linux-image-tools/env.properties#L31

stating that you need to provide either `SSH_PASSWORD` or `SSH_KEY_FILE`.
None of these is mandatory, but you must provide one of them, and if you don't the error message reminds you to do so.

I don't know what else I can add here...

**Comment by delassio** [comment]
i suggest to add into the mandatory section:
 # Root access to the VM. You must provide either a password or a key file.

**Comment by delassio** [comment]
# Custom parameter for the builder
# You can set / override any parameter in this file.
# Alternatively you can use it as a template and pass the actual file as
# parameter to the builder.
# You need at least provide the mandatory parameters

#
# Mandatory parameters
#

# Workspace for the builder and location of the artifacts
WORKSPACE=
# ISO_URL -- location of the ISO file
# Can be local (file://) or remote (https://) but it must be an URL
ISO_URL=
# ISO_CHECKSUM -- checksum for the ISO file
ISO_CHECKSUM=

#
# Optional parameters
#

# Distribution (Default is ol7-slim)
# DISTR=
# Cloud provider (Default is none)
CLOUD="none"

# Build BUILD_NUMBER (Default is 0)
# BUILD_NUMBER=

# Root access to the VM at least one method must be provided:
# Root account password (Default is empty)
# SSH_PASSWORD=
# Path to an ssh private/public key pair (Default none). The public key will
# be installed for the root user
# SSH_KEY_FILE=
# Lock root account after provisioning? (Default: yes)
# LOCK_ROOT=

**Comment by tvierling** [comment]
As noted above, *at least one* of the options is mandatory, and it is documented as such in the env.properties[.defaults] files.
