### ISSUE TITLE
Python3-virtualenv is broken on OL9

### ISSUE THREAD

**Issue by tlaguz** [oracle/oracle-linux#101]
On a clean OL9 install with EPEL repository enabled `oracle-epel-release-el9` I can't install `python3-virtualenv` package because nothing provides `python3-wheel-wheel`:

```
$ sudo dnf install python3-virtualenv
[sudo] password for ewid: 
Last metadata expiration check: 0:05:10 ago on Tue 22 Aug 2023 11:26:41 AM CEST.
Error: 
 Problem: cannot install the best candidate for the job
  - nothing provides python3-wheel-wheel needed by python3-virtualenv-20.20.0-1.el9.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Indeed this package is missing from OL9 repositories: https://pkgs.org/search/?q=python3-wheel-wheel
It is only available in `Oracle Linux CodeReady Builder` but it is marked as unsupported- https://yum.oracle.com/repo/OracleLinux/OL8/codeready/builder/x86_64/index.html ?

**Comment by totalamateurhour** [comment]
The Codeready Builder repository for OL9 also has python3-wheel-wheel. Note that “not supported” here means, not supported as part of an Oracle Linux support subscription the way, say, base OS packages are.  Only installation support is provided, but the same applies to EPEL packages. See the [documentation](https://docs.oracle.com/en/operating-systems/oracle-linux/software-management/sfw-mgmt-HowOracleDistributesSoftwarePackages.html#topic_j4l_zxx_tvb)

**Comment by tlaguz** [comment]
Thank you! Solved by enabling code ready repo:

```
dnf config-manager --enable ol9_codeready_builder
```
