### ISSUE TITLE
dnf update fails du to mismatched package size

### ISSUE THREAD

**Issue by sgatto** [oracle/oracle-linux#112]
Hello,
This is my first issue on this Repo, I hope it's the right place for it.
My company uses OracleLinux 8 and I work on an ope source project that needs to be built for OracleLinux8.
I use docker containers to perform the compilation (CPP).
All the docker based CI action (on Github for example) have been broken for more than 10 days.

Building this dockerfile reproduces the issues:
```
FROM oraclelinux:8
RUN dnf -y update
```
The messages show that all mirrors provide a package with a size that does not match the expected one.
This problem prevents 

```
[MIRROR] libnghttp2-1.33.0-5.el8_9.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 78568 but expected size is: 78564
(76/104): libuuid-2.32.1-43.0.1.el8.x86_64.rpm  1.1 MB/s |  98 kB     00:00    
(77/104): libstdc++-8.5.0-20.0.1.el8.x86_64.rpm 1.4 MB/s | 464 kB     00:00    
(78/104): ncurses-base-6.1-10.20180224.el8.noar 715 kB/s |  81 kB     00:00    
(79/104): ncurses-6.1-10.20180224.el8.x86_64.rp 1.1 MB/s | 387 kB     00:00    
[MIRROR] libnghttp2-1.33.0-5.el8_9.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 78568 but expected size is: 78564
(80/104): ncurses-libs-6.1-10.20180224.el8.x86_ 1.2 MB/s | 334 kB     00:00    
(81/104): oraclelinux-release-el8-1.0-35.el8.x8 277 kB/s |  21 kB     00:00    
[MIRROR] libnghttp2-1.33.0-5.el8_9.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 78568 but expected size is: 78564
[MIRROR] libnghttp2-1.33.0-5.el8_9.x86_64.rpm: Interrupted by header callback: Server reports Content-Length: 78568 but expected size is: 78564
[FAILED] libnghttp2-1.33.0-5.el8_9.x86_64.rpm: No more mirrors to try - All mirrors were already tried without success
```

**Comment by romeroalx** [comment]
I have experienced the same issue today. 

Nevertheless, in case it helps, I did open this same issue last week that was solved temporarily: [https://github.com/oracle/oracle-linux/issues/110](https://github.com/oracle/oracle-linux/issues/110).

**Comment by YoderExMachina** [comment]
We are looking into this.

**Comment by scoter-oracle** [comment]
This issue is confirmed to be fixed.
