### ISSUE TITLE
OL8 linux-firmware update introduces new dependency not available in baseos

### ISSUE THREAD

**Issue by jeepingben** [oracle/oracle-linux#114]
The newest OL8 linux-firmware package has gained a dependency on
`/usr/bin/python3` (from the two new included python scripts as far as
we can tell, `/usr/lib/firmware/build_packages.py` and
`/usr/lib/firmware/contrib/process_linux_firmware.py`) which is a
problem because the packages that provide the python3 binary are not
in the BaseOS repo but are, instead, in the Appstream repository.

Steps to reproduce:
From OL8: `dnf --disablerepo=* --enablerepo=ol8_baseos_latest repoclosure
--nobest --arch x86_64 --arch noarch --check ol8_baseos_latest`

The new scripts appear to only be used by maintainers and can likely be removed during `%install` so they are not delivered in the rpm.

**Comment by tvierling** [comment]
With an update from the upstream linux-firmware repo, we didn't realize that some Python scripts were added to the distribution.

Our fix is going to be switching these to use `platform-python` which is the EL8 "system Python 3" component which is in BaseOS. That will happen at next resync from upstream linux-firmware, which may be in several months. (EL9 reverted back to having a `python3` package in BaseOS so it's not a problem there.)

**Comment by ekarlso** [comment]
Any workaround for this? Seeing it when trying to build a OL8 packer template.

**Comment by warrenridley** [comment]
any fix?

**Comment by tvierling** [comment]
> That will happen at next resync from upstream linux-firmware, which may be in several months.

The fix will be released during the next sync QA cycle. We cannot provide ETAs.

**Comment by YoderExMachina** [comment]
@tvierling, can this issue be closed.  I don't see any errors with python3 when running the repoclosure.

**Comment by tvierling** [comment]
This fix was released in `linux-firmware-20240415-999.32.git5da74b16.el8`.
