### ISSUE TITLE
Is mentioning Fedora in the /etc/os-release file of Oracle Linux 8 misleading?

### ISSUE THREAD

**Issue by kocic11** [oracle/oracle-linux#120]
If Oracle Linux (OL) is like "fedora" (`ID_LIKE="fedora"`), shouldn't it follow the same release convention?

For example, if OL 8 is like Fedora, shouldn't the "releasever" variable have a value of 28? 

In reality, the "releasever" value is 8, which implies that the OL is more aligned with centOS.

**Comment by scoter-oracle** [comment]
ID_LIKE is equal to "fedora" as it is for any other compatible EL distribution (CentOS Linux, CentOS Stream, Rocky Linux and so on). ID is what report to a release.
The same "CentOS Stream" uses "fedora" for ID_LIKE.

**Comment by kocic11** [comment]
It is fine as long as we know what flavour of Linux they are. However, with the OL, this is not the case, and the only clue we have is ID_LIKE. 

This has some material consequences since we can't use the Fedora repos because of the releasever value.

**Comment by tvierling** [comment]
OL has many of the same values in `/etc/os-release` that are present in the equivalent RHEL release. This is to ensure software compatibility with installed packages that expect values similar to RHEL.

You are not supposed to use Fedora packages in OL *at all;* doing so is completely "at your own risk" and unsupported. There is no declared compatibility between Fedora release versions and OL release versions.

**Comment by kocic11** [comment]
I agree, and the only reason I tried that was because of the ID_LIKE. Without any other information, it seemed like a fair assumption.

Can ID_LIKE be updated to represent the OL better?

**Comment by tvierling** [comment]
`fedora` is an appropriate value per the specification for `/etc/os-release` by https://www.freedesktop.org/software/systemd/man/latest/os-release.html

It is the same value used by RHEL and so we use exactly the same value. On Ubuntu, for instance, `ID_LIKE=debian` which does not say anything about Ubuntu.

**Comment by kocic11** [comment]
Yes, I read that. 

I thought that ID_LIKE="rhat fedora"  would be more appropriate.

**Comment by tvierling** [comment]
Generally the `ID_LIKE` value is used to declare the parent distributions of a derivative distribution.

As reiterated in [a recent blog post](https://www.oracle.com/news/announcement/blog/keep-linux-open-and-free-2023-07-10/), Oracle Linux is a *RHEL compatible distribution,* not a direct derivative. The value used is (as mentioned multiple times above) selected to be compatible with RHEL, therefore a matching value.
