### ISSUE TITLE
OL9: Request update lynx to 2.8.9-20.el9 in AppStream

### ISSUE THREAD

**Issue by bthiae2934** [oracle/oracle-linux#128]
lynx 2.8.9-19.el9 can't download file due to RHEL-16809 fixed by lynx-2.8.9-20.el9:
https://access.redhat.com/downloads/content/lynx/2.8.9-20.el9/x86_64/fd431d51/package-changelog
https://gitlab.com/redhat/centos-stream/rpms/lynx/-/commit/e5cd1e1f95f1a1622f1a9cc9fe7bb1a4a305e79f

Could you pull upstream change? I checked Oracle's yum repository and I can't find lynx-2.8.9-20.el9.

**Comment by YoderExMachina** [comment]
Thanks for opening this issue.  I will create an internal ticket to deal with it.

**Comment by YoderExMachina** [comment]
This is now fixed in version 2.8.9-19.0.1.EL9.
