### ISSUE TITLE
OL9: Raspberry PI 5 support?

### ISSUE THREAD

**Issue by manuelsahs** [oracle/oracle-linux#130]
Hello,

any chance to update the Image?

Best Regards

**Comment by tvierling** [comment]
We will evaluate this.

It may require a newer kernel for the hardware support, which OL does not yet ship, and if so it will have to wait until the next major UEK kernel release.

**Comment by tvierling** [comment]
This may be supported in a future release of the UEK kernel. Currently it does not have the necessary hardware drivers for the Pi 5. (Pi devices aren't production-supported, but we do try to run properly on them as long as the necessary drivers are available.)

**Comment by sudo-kraken** [comment]
Any news on this yet?

**Comment by windscale-stephen** [comment]
Apparently the needed drivers etc. were upstreamed in 6.12 - source:

https://www.phoronix.com/news/Linux-6.12-RPi5-More-X1-Laptops
