### ISSUE TITLE
 can yum package manager include video downloader - yt-dlp?

### ISSUE THREAD

**Issue by sword-2** [oracle/oracle-linux#133]
A video downloader was sometimes used because video servers interacted different than simple web pages. Basic terminal tools like curl and wget would not always download videos with a URI / URL. Reference 1 might explain a little bit how video downloads were different. 

The only downloader / tool operated so far in terminal was yt-dlp (reference 2a). This tool was not observed in the yum package manager for OracleLinux_8_7 and Windows Subsystem Linux 2 (WSL2). Yum was not observed in the tool's installation procedures (reference 2b). Also, yt-dlp was not observed in the yum commands listed in Appendix 1.

The yt-dlp tool was currently of interest to download some videos from verse by verse ministry international (https://versebyverseministry.org/). Although verse by verse ministry international was not observed in the supported sites for yt-dlp (reference 2c), I would try anyway. Maybe the site is similar to another supported site and will download? If it doesn't download, maybe a github issue can be submitted to the yt-dlp program to see if the site can be considered?

Reference 2d says the yt-dlp program does not have responsibility to get the tool into the yum package manager for Oracle Linux. The manual download of yt-dlp was not attempted as a workaround since in one instance there was a different issue, not mentioned.

Reference(s)
1.
     Downloading YouTube video. Why it is hard and how can I download it? [closed]
     https://stackoverflow.com/questions/50976256/downloading-youtube-video-why-it-is-hard-and-how-can-i-download-it
2a.
     yt-dlp github web page
     https://github.com/yt-dlp/yt-dlp
2b.
     Installation wiki [yt-dlp not mentioning yum]
     https://github.com/yt-dlp/yt-dlp/wiki/Installation
2c.
     Supported sites
     https://github.com/yt-dlp/yt-dlp/blob/master/supportedsites.md
2d.
     yt-dlp program not responsible for adding tool to yum package manager
     https://github.com/yt-dlp/yt-dlp/issues/9511

Appendix 1 - yum commands attempted to locate yt-dlp tool in OracleLinux_8_7 / WSL2
     yum search dlp
          No matches found.
     yum search yt | grep -iv python
          [omit many results for with keyword python]
     yum list *release-el8*
     yum repolist enabled
     yum repolist disabled
     rpm -q oraclelinux-release-el8
     Some of the above commands were found in the Yum Modularization Update Notice
     https://docs.oracle.com/en/operating-systems/oracle-linux/notice-yum/index.html#action_items

**Comment by tvierling** [comment]
This program is not part of the Oracle Linux base packages and is not planned for inclusion in the production-supported base packages.

It is available for OL9 in the EPEL (Extra Packages for Enterprise Linux) repository, a set of packages which do not receive production support. These packages come from the community EPEL project, which Oracle does not control.

If you want to see it included in EPEL for EL8/OL8, you can ask the community EPEL project about it: https://docs.fedoraproject.org/en-US/epel/
