### ISSUE TITLE
OL9: Request update irqbalance to 1.9.4 to fix regression

### ISSUE THREAD

**Issue by JDPerf** [oracle/oracle-linux#137]
Hello,

As it turns out, `irqbalance` 1.9.2 introduced a performance-impacting regression that was patched by upstream & included in 1.9.4 a few days later:
https://github.com/Irqbalance/irqbalance/issues/301

Downgrading to `irqbalance-1.9.0-3.el9` fixed it for our system. Please either backport their patch or offer 1.9.4 as soon as reasonable. Thanks!

**Comment by YoderExMachina** [comment]
Thanks for raising this issue.  We will look into this.
