### ISSUE TITLE
OL9: The issue with installing the moreutils package.

### ISSUE THREAD

**Issue by maxusotto** [oracle/oracle-linux#138]
To install the moreutils package, files from the "Oracle Linux 9 CodeReady Builder (x86_64) - (Unsupported)" repository are required. Is it normal for the standard repository to lack these packages?

**Comment by YoderExMachina** [comment]
The moreutils package is available in ol9_developer_EPEL.  It is an EPEL package, so that is the correct repo for it.

**Comment by tvierling** [comment]
EPEL packages (which are also unsupported) such as moreutils often require the CodeReady Builder repo to be enabled as well.
