### ISSUE TITLE
OL8.9: dracut fails on aarch64 due to missing xen_netfront

### ISSUE THREAD

**Issue by dedabob** [oracle/oracle-linux#139]
In aarch64 architecture, unlike x86_64, xen drivers are not enabled in kernel but `/etc/dracut.conf.d/01-dracut-vm.conf` contains the line:
```
add_drivers+=" xen_netfront xen_blkfront "
```

When installing new kernels (5.15.0-205.149.5.1.el8uek.aarch64 in my case) the rpm scriptlet reports that dracut failed due to missing xen_netfront module.

As a work-around I removed the line in `/etc/dracut.conf.d/01-dracut-vm.conf`

**Comment by YoderExMachina** [comment]
Where are you seeing the error message?  I tried to duplicate and could not.

`[root@jyoder-ol9-2 ~]# uname -r
5.15.0-203.146.5.1.el8uek.aarch64

[root@jyoder-ol9-2 ~]# dnf update kernel-uek
Ksplice for Oracle Linux 8 (aarch64)                                                                                                                                                11 MB/s | 2.6 MB     00:00    
MySQL 8.0 for Oracle Linux 8 (aarch64)                                                                                                                                              25 MB/s | 3.8 MB     00:00    
MySQL 8.0 Tools Community for Oracle Linux 8 (aarch64)                                                                                                                             3.9 MB/s | 506 kB     00:00    
MySQL 8.0 Connectors Community for Oracle Linux 8 (aarch64)                                                                                                                        427 kB/s |  27 kB     00:00    
Oracle Software for OCI users on Oracle Linux 8 (aarch64)                                                                                                                           55 MB/s | 122 MB     00:02    
Oracle Linux 8 BaseOS Latest (aarch64)                                                                                                                                             101 MB/s | 102 MB     00:01    
Oracle Linux 8 Application Stream (aarch64)                                                                                                                                         89 MB/s |  49 MB     00:00    
Oracle Linux 8 Addons (aarch64)                                                                                                                                                     56 MB/s |  12 MB     00:00    
Latest Unbreakable Enterprise Kernel Release 7 for Oracle Linux 8 (aarch64)                                                                                                         75 MB/s |  31 MB     00:00    
Dependencies resolved.
===================================================================================================================================================================================================================
 Package                                               Architecture                               Version                                                       Repository                                    Size
===================================================================================================================================================================================================================
Installing:
 kernel-uek                                            aarch64                                    5.15.0-205.149.5.1.el8uek                                     ol8_UEKR7                                    2.2 M
 kernel-uek-core                                       aarch64                                    5.15.0-205.149.5.1.el8uek                                     ol8_UEKR7                                     55 M
 kernel-uek-modules                                    aarch64                                    5.15.0-205.149.5.1.el8uek                                     ol8_UEKR7                                     63 M

Transaction Summary
===================================================================================================================================================================================================================
Install  3 Packages

Total download size: 121 M
Installed size: 265 M
Is this ok [y/N]: y
Downloading Packages:
(1/3): kernel-uek-5.15.0-205.149.5.1.el8uek.aarch64.rpm                                                                                                                             27 MB/s | 2.2 MB     00:00    
(2/3): kernel-uek-core-5.15.0-205.149.5.1.el8uek.aarch64.rpm                                                                                                                        60 MB/s |  55 MB     00:00    
(3/3): kernel-uek-modules-5.15.0-205.149.5.1.el8uek.aarch64.rpm                                                                                                                     49 MB/s |  63 MB     00:01    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                               92 MB/s | 121 MB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                           1/1 
  Running scriptlet: kernel-uek-core-5.15.0-205.149.5.1.el8uek.aarch64                                                                                                                                         1/3 
  Installing       : kernel-uek-core-5.15.0-205.149.5.1.el8uek.aarch64                                                                                                                                         1/3 
  Running scriptlet: kernel-uek-core-5.15.0-205.149.5.1.el8uek.aarch64                                                                                                                                         1/3 
  Installing       : kernel-uek-modules-5.15.0-205.149.5.1.el8uek.aarch64                                                                                                                                      2/3 
  Running scriptlet: kernel-uek-modules-5.15.0-205.149.5.1.el8uek.aarch64                                                                                                                                      2/3 
  Installing       : kernel-uek-5.15.0-205.149.5.1.el8uek.aarch64                                                                                                                                              3/3 
  Running scriptlet: kernel-uek-core-5.15.0-205.149.5.1.el8uek.aarch64                                                                                                                                         3/3 
  Running scriptlet: kernel-uek-5.15.0-205.149.5.1.el8uek.aarch64                                                                                                                                              3/3 
  Verifying        : kernel-uek-5.15.0-205.149.5.1.el8uek.aarch64                                                                                                                                              1/3 
  Verifying        : kernel-uek-core-5.15.0-205.149.5.1.el8uek.aarch64                                                                                                                                         2/3 
  Verifying        : kernel-uek-modules-5.15.0-205.149.5.1.el8uek.aarch64                                                                                                                                      3/3 

Installed:
  kernel-uek-5.15.0-205.149.5.1.el8uek.aarch64                     kernel-uek-core-5.15.0-205.149.5.1.el8uek.aarch64                     kernel-uek-modules-5.15.0-205.149.5.1.el8uek.aarch64                    

Complete!
`

**Comment by dedabob** [comment]
I forgot to mention I'm using an AWS EC2 instance with OL8 AMI. I saw those messages in console and I can find them in dnf.rpm.log

```
$ grep -i failed dnf.rpm.log
2024-02-05T15:53:58+0100 INFO dracut-install: Failed to find module 'xen_netfront'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.tDzMvk/initramfs --kerneldir /lib/modules/5.15.0-202.135.2.el8uek.aarch64/ -m xen_netfront xen_blkfront virtio_blk virtio_net virtio_pci virtio_balloon hyperv_keyboard hv_netvsc hid_hyperv hv_utils hv_storvsc hyperv_fb ahci libahci ahci_platform libahci_platform ena nvme nvme_core
2024-02-05T18:30:50+0100 INFO warning: file /boot/dtb-5.15.0-101.103.2.1.el8uek.aarch64: remove failed: No such file or directory
2024-05-03T20:18:55+0200 INFO dracut-install: Failed to find module 'xen_netfront'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.Z2MfNw/initramfs --kerneldir /lib/modules/5.15.0-205.149.5.1.el8uek.aarch64/ -m xen_netfront xen_blkfront virtio_blk virtio_net virtio_pci virtio_balloon hyperv_keyboard hv_netvsc hid_hyperv hv_utils hv_storvsc hyperv_fb ahci libahci ahci_platform libahci_platform ena nvme nvme_core
```

**Comment by dedabob** [comment]
After further investigating I noticed I was using an OL8.8 AMI, so I launched a new instance with OL8.9 AMI but got the same result.
```
$ uname -r
5.15.0-200.131.27.el8uek.aarch64

$ sudo dnf -y update kernel-uek
Last metadata expiration check: 0:02:32 ago on Sun 05 May 2024 06:54:59 PM CEST.
[...]
Running transaction
  Preparing        :                                                                      1/1
  Running scriptlet: kernel-uek-core-5.15.0-205.149.5.1.el8uek.aarch64                    1/3
  Installing       : kernel-uek-core-5.15.0-205.149.5.1.el8uek.aarch64                    1/3
  Running scriptlet: kernel-uek-core-5.15.0-205.149.5.1.el8uek.aarch64                    1/3
  Installing       : kernel-uek-modules-5.15.0-205.149.5.1.el8uek.aarch64                 2/3
  Running scriptlet: kernel-uek-modules-5.15.0-205.149.5.1.el8uek.aarch64                 2/3
  Installing       : kernel-uek-5.15.0-205.149.5.1.el8uek.aarch64                         3/3
  Running scriptlet: kernel-uek-core-5.15.0-205.149.5.1.el8uek.aarch64                    3/3
dracut-install: Failed to find module 'xen_netfront'
dracut: FAILED:  /usr/lib/dracut/dracut-install -D /var/tmp/dracut.eMEMpV/initramfs --kerneldir /lib/modules/5.15.0-205.149.5.1.el8uek.aarch64/ -m xen_netfront xen_blkfront virtio_blk virtio_net virtio_pci virtio_balloon hyperv_keyboard hv_netvsc hid_hyperv hv_utils hv_storvsc hyperv_fb ahci libahci ahci_platform libahci_platform ena nvme nvme_core

  Running scriptlet: kernel-uek-5.15.0-205.149.5.1.el8uek.aarch64                         3/3
  Verifying        : kernel-uek-5.15.0-205.149.5.1.el8uek.aarch64                         1/3
  Verifying        : kernel-uek-core-5.15.0-205.149.5.1.el8uek.aarch64                    2/3
  Verifying        : kernel-uek-modules-5.15.0-205.149.5.1.el8uek.aarch64                 3/3

Installed:
  kernel-uek-5.15.0-205.149.5.1.el8uek.aarch64 kernel-uek-core-5.15.0-205.149.5.1.el8uek.aarch64 kernel-uek-modules-5.15.0-205.149.5.1.el8uek.aarch64

Complete!
```

**Comment by YoderExMachina** [comment]
After some research, we discovered that this is a known issue and is being tracked internally.  It should be resolved with the next image release.
