### ISSUE TITLE
OL8: nagios-plugins-ssl_validity broken dependency on package update

### ISSUE THREAD

**Issue by ku4eto** [oracle/oracle-linux#141]
Hey folks.

Using OL8.9.
Installing `nagios-plugins-all` with all of its dependencies goes just fine.
But upon `dnf update`, it will fail with the following:

```
Error: 
 Problem: cannot install both nagios-plugins-2.3.3-3.el8.x86_64 from ol8_developer_EPEL and nagios-plugins-2.3.3-6.el8.x86_64 from @System
  - cannot install the best update candidate for package nagios-plugins-ssl_validity-2.3.3-6.el8.x86_64
  - cannot install the best update candidate for package nagios-plugins-2.3.3-6.el8.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

Looking around the interwebz, seems like the issue was introduced in 8.2 from the upstream (also present in CentOS 8.2, but got fixed).

A workaround is to exclude the generic package `dnf config-manager --save --setopt ol8_developer_EPEL.exclude=nagios-plugins-2.3.3`, but... its not really a proper workaround either. Does not work to exclude the SSL package.
Another one is to install `nagios-plugins-all`, then remove the `nagios-plugins-ssl_validity` with `--noautoremove` option. But you still end up with a missing package.

**Comment by YoderExMachina** [comment]
How are you installing nagios-plugins-all to begin with?  Seems it was part of the image?

**Comment by ku4eto** [comment]
> How are you installing nagios-plugins-all to begin with? Seems it was part of the image?

Simply `dnf install nagios-plugins-all`, from `@ol8_developer_EPEL`. The "image" is a VM template, configured with bunch of packages and configs. Otherwise is absolutely normal OL8.9, installed from ISO.

**Comment by YoderExMachina** [comment]
Thanks.  We have opened an internal ticket for this issue.

**Comment by elbie1** [comment]
I was able tro reproduce this. It seems like dnf may still be picking up the "osboletes: nagios-plugins-ssl_validity" which is only present in nagios-plugins-2.3.3-3. 
A workaround could be to explicitely exclude that version for dnf by adding "excludepkgs=nagios-plugins-2.3.3-3.el8" in /etc/dnf/dnf.conf

**Comment by ku4eto** [comment]
> I was able tro reproduce this. It seems like dnf may still be picking up the "osboletes: nagios-plugins-ssl_validity" which is only present in nagios-plugins-2.3.3-3. A workaround could be to explicitely exclude that version for dnf by adding "excludepkgs=nagios-plugins-2.3.3-3.el8" in /etc/dnf/dnf.conf. After that you should still be able to update nagios-plugins, it's only that specific -3 version that's being excluded from consideration.

Yes, thats the work around to get `dnf update` to work. but in this case, *ALL* `nagios-plugins-*` packages will not be updated. Furthermore, if you  try doing `dnf install nagios-plugins-XXXX` or reinstall, you will hit an error due to the conflicting exclude and explicitly wanting to re/install that package.

**Comment by elbie1** [comment]
Note that I'm excluding nagios-plugins-2.3.3-3 instead of just nagios-plugins-2.3.3 With that I can downgrade, update again and install  additional plugins.

**Comment by ku4eto** [comment]
Sorry to be a mood killer, but the issue persists.
Did `dnf clean all`, removed `nagios-plugins-all` , which includes the broken package.
Did `dnf update` - works ok.
Installed `nagios-plugins-all` again, which went through.
Doing `dnf update` complains again with:
```
[root@localhost ~]# dnf update
Last metadata expiration check: 0:11:54 ago on 11.06.2024 (вт) 22:42:40 EEST.
Error: 
 Problem: cannot install both nagios-plugins-2.3.3-3.el8.x86_64 from ol8_developer_EPEL and nagios-plugins-2.3.3-6.el8.x86_64 from @System
  - cannot install the best update candidate for package nagios-plugins-ssl_validity-2.3.3-6.el8.x86_64
  - cannot install the best update candidate for package nagios-plugins-2.3.3-6.el8.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```

**Comment by YoderExMachina** [comment]
This version has been removed from the repos.  Please check again.
