### ISSUE TITLE
Slow image build on VirtualBox hosted VM

### ISSUE THREAD

**Issue by malins** [oracle/oracle-linux#146]
Hello,

my image build is very slow on my VirtualBox hosted VM.
I marked the "wait spots" with "???"

```
[ 1725.455887] anaconda[2375]: Performing post-installation setup tasks
[ 1725.527832] anaconda[2375]: Configuring linux-firmware-core.noarch
[ 1726.458642] anaconda[2375]: Configuring filesystem.x86_64
[ 1728.795733] anaconda[2375]: Configuring ca-certificates.noarch
[ 1739.227554] anaconda[2375]: Configuring grub2-common.noarch
[ 1739.621528] anaconda[2375]: Configuring authselect-libs.x86_64
[ 1740.681988] anaconda[2375]: Configuring rpm.x86_64
[ 1741.160816] anaconda[2375]: Configuring selinux-policy-targeted.noarch
[ 1742.282793] anaconda[2375]: Configuring kernel-modules-core.x86_64
[ 1847.319924] anaconda[2375]: Configuring kernel-core.x86_64
??? 54 minutes ???
[ 5092.719286] anaconda[2375]: Configuring kernel-uek-core.x86_64
??? 30 minutes ???
[ 6908.210764] anaconda[2375]: Configuring kernel-modules.x86_64
[ 6908.778233] anaconda[2375]: Configuring kexec-tools.x86_64
[ 6915.486295] anaconda[2375]: Configuring crypto-policies-scripts.noarch
[ 6918.731924] anaconda[2375]: Configuring rootfiles.noarch
[...]
[ 7112.390014] anaconda[2375]: ..
[ 7112.401594] anaconda[2375]: Performing post-installation setup tasks
[ 7114.124532] anaconda[2375]: .
[ 7114.131980] anaconda[2375]: Configuring installed system
[ 7141.144778] anaconda[2375]: ..............
[ 7141.168091] anaconda[2375]: Writing network configuration
[ 7146.558142] anaconda[2375]: .
[ 7146.572663] anaconda[2375]: Creating users
[ 7154.687458] anaconda[2375]: .....
[ 7154.694241] anaconda[2375]: Configuring addons
[ 7155.845786] anaconda[2375]: .
[ 7155.851770] anaconda[2375]: Generating initramfs
??? 89 minutes ???
[12536.084581] anaconda[2375]: ....
[12536.099220] anaconda[2375]: Storing configuration files and kickstarts
[12537.613906] anaconda[2375]: .
[12537.621243] anaconda[2375]: Running post-installation scripts
```

Total time about 4 hours (!)

My configuration:

10 GB of RAM in VM, 4 vCPUs (host system is Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz with a NVMe SSD).
VirtualBox Version 6.1.50 r161033 on Ubuntu 22.04

Any idea what's going on here?

Thank you,
Manuel

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.

This doesn't look to be an issue with the code checked in here on github.  Have you tried building your image outside of VirtualBox?  Have you checked on https://forums.virtualbox.org?
