### ISSUE TITLE
OL8 EPEL Repo comps.xml includes reference to @core with invalid/unavailable package

### ISSUE THREAD

**Issue by viruzeno** [oracle/oracle-linux#150]
I'm seeing an issue with the OL8 EPEL Repo, where the RHC package has been added to the core group in the comps.xml file, however this package is not included in the EPEL repo, and so far as i'm aware it's not supposed to be in here as per the 8.4 release notes, https://docs.oracle.com/en/operating-systems/oracle-linux/8/relnotes8.4/ol8-PackageChangesfromtheUpstreamRelease.html

This can be tested for with dnf install @core after adding the epel repo, I am assuming that the epel repo should not have a core group at all.

See: https://yum.oracle.com/repo/OracleLinux/OL8/developer/EPEL/x86_64/repodata/a28d4cdaedc2f2b2d26d86fe24723494622c50c6ed7bd3b14bca095af074900c-comps.xml

```xml
  <group>
    <id>core</id>
    <name>core</name>
    <description/>
    <default>false</default>
    <uservisible>false</uservisible>
    <packagelist>
      <packagereq type="default">rhc</packagereq>
    </packagelist>
  </group>
  ```

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.

**Comment by YoderExMachina** [comment]
Should be fixed now.
