### ISSUE TITLE
[Oracle 9.4] Kdump test not able to generate logs post command execution

### ISSUE THREAD

**Issue by Ganesh-HPE** [oracle/oracle-linux#153]
[Oracle 9.4] Kdump test not able to generate logs post command execution

Steps to reproduce
Enter BIOS and perform manufacturing defaults.
Make necessary changes in BIOS and save the configuration
Clear all previous partitions on raid controller (SR932i) and create an new virtual disk
Deploy Oracle linux os version 9.4 (OracleLinux-R9-U4x86_64-dvd.iso.iso) on Server
Select default packages for OS installation to proceed
Post OS deployment login to server and trigger crash by executing command
echo c > /proc/sysrq-trigger
Note the command execution is successful and server gets rebooted
Post server reboots we do not see any crash files in var/crash folder

NOTE: Same crash dump works on same server with RHEL 9.4 GA build.

Configuration Details

Server - DL325 Gen11
System ROM - A56 v1.22 (01/19/2023)
iLO Firmware Version -1.30 Feb 28 2023
Processor - AMD EPYC 9754 128-Core Processor
Memory - 16 GB 4800 MHz
Storage Controller - HPE SR932i-p Gen11
Network Card - Adapter 1 - 10/25Gb 2-port SFP28 BCM57414 OCP3 Adapter

Adapter 2 - Intel(R) Eth E810-2CQDA2
[Uploading sosreport-localhost-2024-08-02-alocfuq.zip…]()

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.

**Comment by YoderExMachina** [comment]
Can't duplicate this.  Granted I'm using different hardware, but all else is the same.  I recommend you connect to the console when you sysrq the system.  That will allow you to troubleshoot further.
