### ISSUE TITLE
Missing icon on KDE panel

### ISSUE THREAD

**Issue by natomist** [oracle/oracle-linux#154]
Step to reproduce problem:
1. Install Oracle Linux 9.4 with option "Minimal Install"
2. Enable `CodeReady` repository
3. Install `oracle-epel-release-el9`
4. Install group `kde-desktop-environment`
5. switch default target to `graphical.target` for systemctl
6. reboot

Everything works fine except for the lack of an icon on the application launcher button:
![image](https://github.com/user-attachments/assets/daf956d9-b6a1-4bc7-89f0-ae755f466974)

On Rocky Linux and CentOS, the same steps will get you a panel with an icon on the button.

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.

**Comment by natomist** [comment]
I'm not a customer.
Could you explain where exactly I can post issue at https://support.oracle.com?

**Comment by YoderExMachina** [comment]
You can't if you are not a customer.  As the comment above states, "if we can confirm that an issue is a bug we will do our best to fix it and to update this issue once it has been fixed."

**Comment by YoderExMachina** [comment]
I don't actually see `kde-desktop-environment` as an option after enabling EPEL.  Can you provide the exact commands you are running?

**Comment by natomist** [comment]
2. `sudo dnf config-manager --set-enabled ol9_codeready_builder`
3. `sudo dnf install oracle-epel-release-el9`
4. `sudo dnf install @kde-desktop-environment`
4.1. `sudo dnf install plasma-milou` - krunner doesn't work without this package
6. `sudo systemctl set-default graphical.target`
7. `reboot`
After these commands you will get KDE desktop environment. Everything works fine except "launch application button on the panel"

**Comment by YoderExMachina** [comment]
Thanks, not sure why this wasn't working for me before.
