### ISSUE TITLE
ERROR    cannot set CPU affinity on process 5764: Invalid argument

### ISSUE THREAD

**Issue by IgorM24** [oracle/oracle-linux#155]
Hi!

WhenI try build ol9-slim for vbox, got error:

My env.properties:
WORKSPACE=/vmimages/oel9_light_vbox
ISO_URL=file:////tmp/OracleLinux-R9-U4-x86_64-boot-uek.iso
ISO_CHECKSUM=0e83d2211925bd51a84cc9321f90a6a4ccbc83cf567e393b75c23b0f6745c1f4
CLOUD=vagrant-virtualbox
DISTR="ol9-slim"
VAGRANT_GUEST_ADDITIONS_URL=file:////tmp/VBoxGuestAdditions.iso
VAGRANT_GUEST_ADDITIONS_SHA256=4c7523fa6d17436e3b7788f62956674270572cfefa340d03111b85f8517d5981

Error log:

```
[oracle@localhost ~]$ ./oracle-linux/oracle-linux-image-tools/bin/build-image.sh --env env.properties
+++ build-image.sh: Parse arguments
+++ build-image.sh: Load environment
+++ build-image.sh: Retrieve installation media VBoxGuestAdditions.iso
    build-image.sh: using cached file /vmimages/oel9_light_vbox/.cache/e7a15444271531ee7ffde9f065f73e48399da796-VBoxGuestAdditions.iso
+++ build-image.sh: Retrieve installation media OracleLinux-R9-U4-x86_64-boot-uek.iso
    build-image.sh: using cached file /vmimages/oel9_light_vbox/.cache/9088f778776b6a3f71544a85ed3a95147867b57e-OracleLinux-R9-U4-x86_64-boot-uek.iso
+++ build-image.sh: Stage provisioning files
+++ build-image.sh: Stage kickstart file
+++ build-image.sh: Install Oracle Linux
WARNING  --os-type is deprecated and does nothing. Please stop using it.

Starting install...
Retrieving 'vmlinuz'                                                                                                                                                  |  13 MB  00:00:00
Retrieving 'initrd.img'                                                                                                                                               |  95 MB  00:00:00
Allocating 'OL9U4_x86_64-vagrant-virtualbox-b0.qcow2'                                                                                                                 |  15 GB  00:00:00
Removing disk 'OL9U4_x86_64-vagrant-virtualbox-b0.qcow2'                                                                                                              |         00:00:00
ERROR    cannot set CPU affinity on process 5764: Invalid argument
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///session start OL9U4_x86_64-vagrant-virtualbox-b0
otherwise, please restart your installation.



```

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.
