### ISSUE TITLE
[createrepo] uln-yum-mirror script misjudges RAM to determine --update option

### ISSUE THREAD

**Issue by EmersonPrado** [oracle/oracle-linux#162]
> Follow up to [this community discussion](https://community.oracle.com/mosc/discussion/4575842/createrepo-update-needs-6gb-ram-but-tests-if-there-is-5000mb-only)

This is an obsolete setup (RHEL 6.8 + uln-yum-mirror 0.3.0-3), but the problem and the solution are so simple I guess it's worth a try. I surely know the proper solution is an upgrade, but this is beyond my decision power.

This excerpt from `/usr/bin/uln-yum-mirror` seems to do the wrong test to check if RAM is enough to enable createrepo's `--update` option:

```Shell
case $EL_VER in
    [5-7])
        # We need 6GB of memory, but check if it's greater than 5000 to allow for reserved memory and kdump
        # Anything less and createrepo --update is very likely to trigger the OOM-killer for large repos
        # This will cause the createrepo process to take longer, but at least it will finish
        if [ "$(free -m | awk '/Mem/{print $2}')" -ge 5000 ]; then
            CREATEREPO_EXTRA_ARGS+="--update"
        fi
```

It seems clear that, if `--update` option needs 6GB, and the script wants to allow for other system stuff, then it should test for *more* than 6GB, but it tests for *less*. So, if RAM is between 5000MB and 6GB+, the script takes the wrong decision, includes `--update` option, then `createrepo` exhausts RAM and draws in some swap and the risk of OOM. And indeed, we fell in this situation here once.

According to the community discussion, this is still the case in latest versions of uln-yum-mirror, so the problem persists.

So this is a very simple request, I guess:
Is it possible to change the 5000 for something which does allow for 6GB, reserved memory and kdump?

**Comment by tvierling** [comment]
Note, uln-yum-mirror is no longer supported on OL6/EL6 (has not been since 2021), the script will be going out of support soon on OL7, and mirrors should be upgraded to OL9 or OL8 as soon as you can do so. (Further, mirroring OL9 or OL8 repos on OL7 or OL6 is not supported and will cause modular package failures.)

Please check out the newer mirroring instructions based on OL9/OL8 and consider moving to that soon: https://docs.oracle.com/en/operating-systems/oracle-linux/software-management/sfw-mgmt-SetUpLocalULNMirror.html

If you have further ULN problems, please file an Oracle Support case under your CSI.

**Comment by EmersonPrado** [comment]
> Note, uln-yum-mirror is no longer supported on OL6/EL6 (has not been since 2021), the script will be going out of support at end of 2024 on OL7...

Hi, @tvierling ! This is a very interesting info. Do you know of any life cycle docs I could reference? This would be very useful to internally push for mirror migration (and, I still hope, upgrade the ancient OS).

**Comment by trix1100** [comment]
https://www.oracle.com/a/ocom/docs/elsp-lifetime-069338.pdf

**Comment by EmersonPrado** [comment]
@tvierling I guess I misunderstood things. So our mistake is not using ULN, but using an obsolete ULN setup - the one based on OL6/7? In this case, if we update to the current ULN setup as you mentioned, can we still use them to mantain our obsolete and unsupported OL6/7 servers?

**Comment by trix1100** [comment]
Yes, an OL8/OL9 dnf reposync based mirror supports mirroring OL6-OL9 channels, whereas OL6/OL7 uln-yum-mirror based only supports mirroring OL6/OL7 content. Refer: Oracle Linux: Supported ULN / YUM Software Mirroring Methods (Doc ID 2969047.1)
