### ISSUE TITLE
Freeradius not built against OpenSSL 3.2.2

### ISSUE THREAD

**Issue by archset** [oracle/oracle-linux#163]
Freeradius fails after update to OpenSSL 3.2.2 (OL 9.5) - expects 3.0.7. Freeradius package in appstream needs to be rebuilt against OpenSSL 3.2.2

## Error

```
[root@test ~]# RADIUS_MD5_FIPS_OVERRIDE=1 radiusd -X
libssl version mismatch.  built: 30000070 linked: 30200020
[root@test ~]#
```
## Package Info

```
Name         : freeradius
Version      : 3.0.21
Release      : 42.el9
Repository   : ol9_appstream
```
```
Name         : openssl
Epoch        : 1
Version      : 3.2.2
Release      : 6.0.1.el9_5
Repository   : ol9_baseos
```

Current workaround requires downgrading OpenSSL back to 3.0.7.

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.

**Comment by YoderExMachina** [comment]
freeradius-3.0.21-43.el9_5.x86_64 has been released.
