### ISSUE TITLE
yum update changed mode of /root ?

### ISSUE THREAD

**Issue by don-git** [oracle/oracle-linux#164]
I don't know which update and can't even prove that this was done by yum update
but that's my only candidate so far.  Unfortunately this was my first update in a long time
(close to a year) so there were a lot of packages to upgrade and I have no idea which one
did it.  
I did see some warnings but nothing about changing /root.
I hope there's no NEED to change the mode of root and of course that made certain 
things not work for me until I figured out the problem and fixed it.
I now worry what else might have been "fixed" for me that will cause things to break.

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.

**Comment by YoderExMachina** [comment]
Unfortunately, I can't open a bug as there is not enough to go on.  I don't know what OS version you are running, what versions you updated to, why you suspect yum, or even what the changes were to root.

**Comment by don-git** [comment]
Jeffery Yoder writes:
 > Unfortunately, I can't open a bug as there is not enough to go on.  I don't know what OS version you are running, what versions you updated to, why you suspect yum, or even what the changes were to root.

oracle linux 9.  I've now managed (with difficulty) to login to support.oracle.com
and I don't see how to submit a bug report.
Give me a hint how to do that.

**Comment by YoderExMachina** [comment]
If you're not an Oracle Customer you won't be able to log a Service Request.  Here is the procedure just in case: https://www.oracle.com/assets/support-process-guide-cloud-4428288.pdf.

I will open a bug for this and wait to see if anyone else reports this.

**Comment by don-git** [comment]
I've opened SR=4-0000139788
I guess that's how you're supposed to report bugs?
(Seems strange to me...)

Jeffery Yoder writes:
