### ISSUE TITLE
osinfo-db is missing RHEL 9.5 and breaks libvirt/virsh

### ISSUE THREAD

**Issue by JDTX0** [oracle/oracle-linux#165]
After upgrading to `osinfo-db-20231215-1.0.2.el8.noarch` on an Oracle 8 system, `virsh define` no longer works and throws an error about a missing RHEL 9.5 definition:

```
** (process:82156): WARNING **: 07:38:10.006: Entity http://redhat.com/rhel/9.5 referenced but not defined
ERROR    list index out of range
error: failed to get domain 'redacted'
error: failed to get domain 'redacted'
error: failed to get domain 'redacted'
error: Failed to define domain from /tmp/virsh_xml.82066
error: (domain_definition):2: Start tag expected, '<' not found
(null)
^
error: failed to get domain 'redacted'
```

Downgrading osinfo-db to `osinfo-db-20231215-1.0.1.el8.noarch` fixes the issue.

Tracing the error down, I found that `osinfo-query` has an invalid entry for RHEL 9.5:
```shell
 osinfo-query os | grep -i rhel | tail -n 3

** (osinfo-query:31144): WARNING **: 10:27:41.998: Entity http://redhat.com/rhel/9.5 referenced but not defined
 rhel9.3              | Red Hat Enterprise Linux 9.3                       | 9.3      | http://redhat.com/rhel/9.3              
 rhel9.4              | Red Hat Enterprise Linux 9.4                       | 9.4      | http://redhat.com/rhel/9.4              
                      |                                                    |          | http://redhat.com/rhel/9.5
```

Going down further, the src RPM for osinfo-db had this patch added in the new version:
```
grep "rhel/9.5" *.patch
103-orabug37315406-Add-OL9.5-XML.patch:+    <clones id="http://redhat.com/rhel/9.5"/>
```

The relevant changelog entry for the RPM (and the corresponding Oracle bug #) is:
```
2024-11-27 - Kevin Lyons <kevin.x.lyons@oracle.com> - 20231215-1.0.2
- Add OL9.5 data [Orabug: 37315406]
```

This patch adds OL 9.5, but the XML makes a reference to RHEL 9.5 which wasn't added and causes that bad entry in osinfo-db:
```shell
find /usr/share/osinfo/os/redhat.com -type f -name "rhel-9.*"
/usr/share/osinfo/os/redhat.com/rhel-9.3.xml
/usr/share/osinfo/os/redhat.com/rhel-9.1.xml
/usr/share/osinfo/os/redhat.com/rhel-9.0.xml
/usr/share/osinfo/os/redhat.com/rhel-9.4.xml
/usr/share/osinfo/os/redhat.com/rhel-9.2.xml
```

The XML for RHEL 9.5 can be found upstream in libosinfo [here](https://gitlab.com/libosinfo/osinfo-db/-/blob/main/data/os/redhat.com/rhel-9.5.xml.in?ref_type=heads)

Can this please be fixed?

Thank you!

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.

**Comment by JDTX0** [comment]
@YoderExMachina Looks like this was fixed in https://linux.oracle.com/errata/ELBA-2024-12888.html

Thank you!
