### ISSUE TITLE
Can't disable MCE correctable errors and EDAC according to HPE recommendation

### ISSUE THREAD

**Issue by feldsam** [oracle/oracle-linux#166]
Hello, we upgraded server to DL325 GEN10 PLUS V2 with AMD EPYC Milan CPU. We constantnly see mce hardware errors in dmesg and on screen.

To Ensure Efficient Firmware First Handling of Memory Failures HPE Recommends Booting With the mce=ignore_ce Boot Parameter in Addition to Disabling EDAC
ref: https://support.hpe.com/hpesc/public/docDisplay?docId=a00016026en_us&docLocale=en_US

Linux - Correctable Errors (CE) Similar to "[Hardware Error]: CPU:0 (17:31:0) MC255_STATUS[-|CE|-|-|AddrV|-|-|-]" May Be Logged in dmesg on HPE ProLiant Gen10 Plus Systems with an AMD Processor
ref: https://support.hpe.com/hpesc/public/docDisplay?docId=a00125537en_us&docLocale=en_US

How we can get rid of this specific "MC255_STATUS" error logged?

We tried to boot with kernel params `edac_report=off ghes.disable=1 mce=ignore_ce` and also created file `/etc/modprobe.d/blacklist.conf` with the following contents

```
blacklist edac_mce_amd
install edac_mce_amd /bin/false
```

SR 3-39123353001

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.

**Comment by feldsam** [comment]
Hello, on retired bugzilla site you have written:

```
Oracle Linux users with a support subscription should contact MyOracle support for software assistance.
Users without an Oracle Linux Support subscription can report issues through the [Oracle Linux Github](https://github.com/oracle/oracle-linux/issues).
```

So why you are closing this? Anyway, I also reported this through SR, but communication with first level support guys is very challenging. Looks like they don't know what I am asking for.
