### ISSUE TITLE
python3-kickstart is missing support for the new "ostreecontainer" command

### ISSUE THREAD

**Issue by fpoirotte** [oracle/oracle-linux#167]
Hello,

I have created my own bootc-compatible container image based on Oracle Linux 9.5.
I would like to install said container image automatically using anaconda/kickstart.

When using an ISO derived from RHEL, this is possible using the anaconda/kickstart "ostreecontainer' command.
When I try to replicate this result using the OL-based ISO, I get an error stating that "ostreecontainer" is an unknown command.
![Screenshot_oraclelinux-server-9 20241228 0 5-bootc_2024-12-28_23:14:58](https://github.com/user-attachments/assets/81b7934e-5c07-4863-95cf-f12b17833b60)

Looking at the code in python3-kickstart (in particular, `/usr/lib/python3.9/site-packages/pykickstart/handlers/ol9.py`), I see that it is indeed missing the definition for the command when compared to `handlers/rhel9.py`.

<details>
<summary>Handler used by Oracle Linux 9</summary>

![ol9_handler](https://github.com/user-attachments/assets/6d0fbacf-d887-4604-a451-765d6adee258)

</details>

<details>
<summary>Handler used by RHEL 9</summary>

![rhel9_handler](https://github.com/user-attachments/assets/a38dfa8a-f223-45af-9528-7dff7d5450d8)

</details>

Would it be possible to update the anaconda package to include the new command?
In addition, does Oracle intend to provide official bootc images?

**Comment by YoderExMachina** [comment]
Oracle Linux customers, please file your issue at https://support.oracle.com

Thanks for filing an issue with Oracle Linux. 

GitHub Issues is not an official support channel and we don't offer 
product support here. If you're not yet an Oracle Linux customer, 
consider signing up at https://linux.oracle.com. 

Even if you're not a customer, if we can confirm that an issue is a 
bug we will do our best to fix it and to update this issue 
once it has been fixed. We don't guarantee a fix or feedback and
for now, we will close this issue. If you have Oracle Linux support, 
please use support.oracle.com to report issues.

**Comment by YoderExMachina** [comment]
You don't mention the version of python3-kickstart you have installed, so I will assume it's the latest.

**Comment by YoderExMachina** [comment]
Actually ostreecontainer is in the latest version.  

`$ rpm -q python3-kickstart
python3-kickstart-3.32.11-1.0.1.el9.noarch
`

**Comment by fpoirotte** [comment]
Hello,

Thank you for taking the time to look into this and sorry if my initial report was missing the package's version.

I was indeed referring to python3-kickstart-3.32.11-1.0.1.el9.noarch.
I just checked and can confirm that ostreecontainer is missing from the OL9 handler (overall support for the command is present in the package, but unless it is actively listed in the handler, it cannot be used -- that's why it works for RHEL but not OL).

Per your initial reply, I'll try opening a case at https://linux.oracle.com/

Best regards,
François
