### ISSUE TITLE
Samba4

### ISSUE THREAD

**Issue by paulecyr** [oracle/oracle-linux#47]
Instalador Samba4

**Comment by totalamateurhour** [comment]
Do you have an issue with Samba 4 on Oracle Linux? If so, please provide more details.

**Comment by paulecyr** [comment]
Estou utilizando a versão oracle linux 7.9, ao tentar instalar o samba-4.15.2 seguindo manual do samba.org "Package Dependencies Required to Build Samba Install the following packages to build Samba as an Active Directory (AD) domain controller (DC) on a minimal Red Hat Enterprise Linux 7" não funcionou por não encontrar alguns packages necessário, consegui instalar somente a versão samba-4.8.12

**Comment by totalamateurhour** [comment]
I recommend you use Oracle Linux 8. It comes with Samba 4.x included.

**Comment by totalamateurhour** [comment]
I'm closing this issue. Please re-open if you encounter any issues with Samba 4 on Oracle Linux 8.
