### ISSUE TITLE
"dnf needs-restarting  -r" Always reporting a reboot is required

### ISSUE THREAD

**Issue by Matty-uk** [oracle/oracle-linux#81]
We are running various servers using Oracle Linux 8 both on aarch64 and x86-64 architecture.  Recently we have rolled out a monitoring check to determine if servers are reporting if a reboot is need.  We do this via using the results from the "dnf needs-restarting  -r".

We have discovered that on aarch64 Oracle Linux 8 always reports back that a reboot is need, results as follows:
> Core libraries or services have been updated since boot-up:
>   * dbus
>   * dbus-daemon
>   * glibc
>   * linux-firmware
>   * systemd
> 
> Reboot is required to fully utilize these updates.
> More information: https://access.redhat.com/solutions/27943

Obviously after a reboot the server(s) should not be reporting that a reboot is required.

**Comment by totalamateurhour** [comment]
What version `dnf` are you running here?

**Comment by Matty-uk** [comment]
dnf --version
4.7.0
  Installed: dnf-0:4.7.0-11.0.1.el8.noarch at Wed 23 Nov 2022 03:41:05 PM GMT
  Built    :  at Tue 04 Oct 2022 08:50:36 PM GMT

  Installed: rpm-0:4.14.3-24.el8_7.aarch64 at Wed 23 Nov 2022 03:39:56 PM GMT
  Built    :  at Thu 10 Nov 2022 06:41:59 PM GMT

**Comment by totalamateurhour** [comment]
And what kind of CPUs?

```
lscpu
cat /proc/cpuinfo
```

**Comment by Matty-uk** [comment]
cat /proc/cpuinfo
processor       : 0
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 1
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 2
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

processor       : 3
BogoMIPS        : 108.00
Features        : fp asimd evtstrm crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x0
CPU part        : 0xd08
CPU revision    : 3

**Comment by Matty-uk** [comment]
lscpu
Architecture:        aarch64
Byte Order:          Little Endian
CPU(s):              4
On-line CPU(s) list: 0-3
Thread(s) per core:  1
Core(s) per cluster: 4
Socket(s):           1
Cluster(s):          1
NUMA node(s):        1
Vendor ID:           ARM
BIOS Vendor ID:      Unknown
Model:               3
Model name:          Cortex-A72
BIOS Model name:     Unknown
Stepping:            r0p3
CPU max MHz:         1500.0000
CPU min MHz:         600.0000
BogoMIPS:            108.00
NUMA node0 CPU(s):   0-3
Flags:               fp asimd evtstrm crc32 cpuid

**Comment by Matty-uk** [comment]
On Raspberry Pi 4b if that helps.

**Comment by totalamateurhour** [comment]
That RPi doesn’t have a real time clock, correct? Looks like there is a fix upstream for this issue. Looking into it.

**Comment by Matty-uk** [comment]
Correct, there is no real time clock.  Plus thanks for looking into it.

**Comment by totalamateurhour** [comment]
We've confirmed this issue on a Raspberry Pi without RTC and releasing a fix is being investigated. Meanwhile, you could choose to apply this patch: https://patch-diff.githubusercontent.com/raw/rpm-software-management/dnf-plugins-core/pull/468.patch to `/usr/lib/python3.6/site-packages/dnf-plugins/needs_restarting.py`

**Comment by Matty-uk** [comment]
I've made the changes from the patch to one of the hosts, however the results remain the same.

I've attached copies for the file: before and after.
[needs_restarting.zip](https://github.com/oracle/oracle-linux/files/11403991/needs_restarting.zip)

**Comment by AmedeeBulle** [comment]
This is weird...
We have tested this on several Raspberry Pi (without RTC), and it worked flawlessly.
Is your clock accurate when you are running `dnf needs-restarting`, and was it accurate when you installed the packages?
It looks like as either your clock is in the past or it was in the future when you last installed packages...

Can you run the following `check_clock.py` script on your patched host?

```python
#!/usr/bin/env python3

import datetime
import dnf
import os
import time

NEED_REBOOT = ['kernel', 'kernel-rt', 'glibc', 'linux-firmware',
               'systemd', 'dbus', 'dbus-broker', 'dbus-daemon']

print("===== Clocks =====")
print(f"SC_CLK_TCK    : {datetime.datetime.fromtimestamp(os.sysconf_names['SC_CLK_TCK'])}")

proc_1_boot_time = int(os.stat('/proc/1').st_mtime)
print(f"/proc/1       : {datetime.datetime.fromtimestamp(proc_1_boot_time)}")

now = time.time()
print(f"Now           : {datetime.datetime.fromtimestamp(now)}")
with open('/proc/uptime', 'rb') as f:
    uptime = f.readline().strip().split()[0].strip()
print(f"Uptime        : {datetime.timedelta(seconds=float(uptime))}")

proc_uptime_boot_time = int(time.time() - float(uptime))
print(f"Boot time     : {datetime.datetime.fromtimestamp(proc_uptime_boot_time)}")
boot_time = max(proc_1_boot_time, proc_uptime_boot_time)
print(f"Returned time : {datetime.datetime.fromtimestamp(boot_time)}")

print("===== Packages =====")
with dnf.Base() as base:
    # base.read_all_repos()
    # base.fill_sack_from_repos_in_cache(load_system_repo=False)
    conf = base.conf
    base.fill_sack()
    installed = base.sack.query().installed()
    for pkg in installed.filter(name=NEED_REBOOT):
        print(f"{pkg.name:15}: {datetime.datetime.fromtimestamp(pkg.installtime)}{' - Updated' if pkg.installtime > boot_time else ''}")
```

In my case, output is consistent with `dnf needs-restarting -r`:

```
$ sudo dnf needs-restarting -r
Core libraries or services have been updated since boot-up:
  * glibc

Reboot is required to fully utilize these updates.
More information: https://access.redhat.com/solutions/27943
$ ./check_clock.py 
===== Clocks =====
SC_CLK_TCK    : 1970-01-01 00:00:02
/proc/1       : 1970-01-01 00:00:05
Now           : 2023-05-05 09:34:31.006862
Uptime        : 258 days, 19:37:45.220000
Boot time     : 2022-08-19 13:56:45
Returned time : 2022-08-19 13:56:45
===== Packages =====
dbus           : 2022-04-01 13:09:13
dbus-daemon    : 2022-04-01 13:08:57
glibc          : 2023-01-16 19:41:09 - Updated
linux-firmware : 2022-04-01 13:14:42
systemd        : 2022-04-01 13:09:18
```

**Comment by Matty-uk** [comment]
Here's the results:

./check_clock.py
===== Clocks =====
SC_CLK_TCK    : 1970-01-01 01:00:02
/proc/1       : 1970-01-01 01:00:05
Now           : 2023-05-09 11:23:21.957648
Uptime        : 4 days, 3:22:50.830000
Boot time     : 2023-05-05 08:00:31
Returned time : 2023-05-05 08:00:31
===== Packages =====
dbus           : 2023-02-02 15:08:43
dbus-daemon    : 2023-02-02 15:08:38
glibc          : 2022-11-23 14:58:17
linux-firmware : 2023-04-18 10:09:31
systemd        : 2023-03-28 09:09:18
