### ISSUE TITLE
"intel corporation alder lake-p pch cnvi wifi (rev 01)" iwlwifi driver missing in ol8.7

### ISSUE THREAD

**Issue by ken-bell** [oracle/oracle-linux#86]
The iwlwifi driver for the "intel corporation alder lake-p pch cnvi wifi (rev 01)" adapter is missing from kernels 5.15.0-3.60.5.1.el8uek.x86_64 (original with release 8.7) and 5.15.0-100.96.32.el8uek.86_64 (current update).  No problem with the 4.18 kernels though.

**Comment by ken-bell** [comment]
Still missing in 5.15.0-101.103.2.1.el8uek.x86_64

**Comment by totalamateurhour** [comment]
The iwlwifi module should be there, but it's possible your device is not included, especially if it's a desktop or laptop device. Do you know its device ID? Can you show any additional troubleshooting you've done?

**Comment by ken-bell** [comment]
The adapter is in an HP EliteBook 640 notebook.

Sorry, yes, the iwlwifi module is present (and loaded in both the 4 and 5 kernels), but in 5 the iwlmvm and mac80211 modules do not get loaded automatically by iwlwifi (although they too are present on disk).  It's not actually missing.

If I manually load iwlmvm under the 5 kernel, or if I have it load automatically via /etc/modules-load.d, the wifi interface does not appear when queried by ifconfig.

I'm not sure what else to do to troubleshoot this.    Thanks.

[wifi.kernel-5.txt](https://github.com/oracle/oracle-linux/files/11536543/wifi.kernel-5.txt)
[wifi.kernel-4.txt](https://github.com/oracle/oracle-linux/files/11536544/wifi.kernel-4.txt)

**Comment by totalamateurhour** [comment]
What does `dmesg` show?

```
dmesg | grep iwlwifi

**Comment by ken-bell** [comment]
Bingo!  (newer firmware needed)

[typescript.kernel-4_dmesg.txt](https://github.com/oracle/oracle-linux/files/11537087/typescript.kernel-4_dmesg.txt)
[typescript.kernel-5_dmesg.txt](https://github.com/oracle/oracle-linux/files/11537088/typescript.kernel-5_dmesg.txt)
