### ISSUE TITLE
kernel panic on degraded md array

### ISSUE THREAD

**Issue by YoshinoriSato-STI** [oracle/oracle-linux#89]
I tried degraded md in OL8U7 kernel.
I got  this panic message.

[ 5354.178618] BUG: kernel NULL pointer dereference, address: 0000000000000120
[ 5354.178962] blk_update_request: I/O error, dev nbd1, sector 8388096 op 0x1:(WRITE) flags 0x0 phys_seg 4 prio class 0

Full dmesg attached. And I have vmcore so I can provide it.
[vmcore-dmesg.txt.gz](https://github.com/oracle/oracle-linux/files/11673457/vmcore-dmesg.txt.gz)

**Comment by tvierling** [comment]
I'm sorry this report was overlooked, but there have been many md fixes in UEK7 in the time since you posted this issue. Can you retry and see if this reproduces on an up-to-date system?

**Comment by YoshinoriSato-STI** [comment]
Thanls comment.
I will try 5.15.0-8.91.4.1.el8uek.x86_64.
This problem is not reproducible, so it will take a few days to confirm.

**Comment by YoshinoriSato-STI** [comment]
I checked with 5.15.0-8.91.4.1.el8uek.
Since a kernel panic occurs due to a different problem, it is not possible to confirm whether this problem has been fixed.
Should I register a new issue for a new problem?

**Comment by YoshinoriSato-STI** [comment]
I also tried newer releases.
kernel-uek-5.15.0-200.119.13.el8uek.x86_64.rpm
kernel-uek-5.15.0-204.147.6.el8uek.x86_64.rpm
These two results were as expected.
I haven't tried the others, but this problem doesn't seem to occur if the patch level is 200 or higher.
Thanks.
