### ISSUE TITLE
The trust relationship between this workstation and the primary domain failed

### ISSUE THREAD

**Issue by bunkobugsy** [oracle/oracle-linux#92]
Error shown: "The trust relationship between this workstation and the primary domain failed." on domain logon or net connect to Windows 10/11 PDC joined workstations since July 2023 updates KB5028166 / KB5028185

component: samba-4.10.16-24.0.1.el7_9.x86_64

available patch: https://bugzilla.samba.org/show_bug.cgi?id=15418#c25
https://cpaste.org/?df0494cac0063e2e#Cx69G684EBPQ71S6sAUVXSYburgV6gPyKHfPSbfmHZPJ

[trust.patch](https://github.com/oracle/oracle-linux/files/12067224/trust.patch) adapted for 4.10.16-24

**Comment by tvierling** [comment]
Please check whether latest samba (4.10.16-25.0.1) fixed the issue for you, as there are Netlogon fixes added in that revision.

**Comment by tvierling** [comment]
Actually, looks like an updated version of the patch above is indeed included in -25.0.1; closing as fixed.
