### ISSUE TITLE
selinux-policy package is outdated and breaks dependencies

### ISSUE THREAD

**Issue by sjkjs** [oracle/oracle-linux#93]
I am unable to update zabbix-agent on Oracle Linux 9 due to the selinux-policy package being outdated.

The latest zabbix-agent is:

https://yum.oracle.com/repo/OracleLinux/OL9/developer/EPEL/x86_64/getPackage/zabbix-agent-6.0.18-1.el9.x86_64.rpm

It requires zabbix-selinux as a dependency:

https://yum.oracle.com/repo/OracleLinux/OL9/developer/EPEL/x86_64/getPackage/zabbix-selinux-6.0.18-1.el9.noarch.rpm

zabbix-selinux requires these dependencies:

selinux-policy >= 38.1.11-2.0.1.el9_2.3
selinux-policy-base >= 38.1.11-2.0.1.el9_2.3

Oracle Linux 9 repositories do not provide these versions. The latest version is:

https://yum.oracle.com/repo/OracleLinux/OL9/baseos/latest/x86_64/getPackage/selinux-policy-38.1.11-2.0.1.el9_2.2.noarch.rpm

The difference being el9_2.2 vs el9_2.3.

It's been broken for a few months now. I had hoped that if I just waited it would resolve itself, but it's still broken as of today.

This is not an issue in other RHEL9 based distros e.g. CentOS Stream 9, Rocky Linux 9. How do I get this fixed in Oracle Linux?

**Comment by guruguruguru** [comment]
We have the same issue, will there anything be done about this?

**Comment by totalamateurhour** [comment]
Apologies. Release is being worked on.

**Comment by rasgard** [comment]
same issue with ipa-4.10.1-8.0.1.el9_2 do you test your pacages on  rhel ;)

**Comment by totalamateurhour** [comment]
https://yum.oracle.com/repo/OracleLinux/OL9/baseos/latest/x86_64/getPackage/selinux-policy-38.1.11-2.0.1.el9_2.3.noarch.rpm

It’s been released.

**Comment by sjkjs** [comment]
Thank you. The issue is now resolved.
